[window]
startup_mode = "Maximized"

[font]
normal.family = "ComicShannsMono Nerd Font"
bold.family = "ComicShannsMono Nerd Font"
italic.family = "ComicShannsMono Nerd Font"
bold_italic.family = "ComicShannsMono Nerd Font"
size = 17.0

[mouse]
hide_when_typing = true
